package com.itany.nmms.entity;

import java.util.Date;

public class Attache {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attache.attache_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer attacheId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attache.file_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attache.file_path
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attache.create_date
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attache.user_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attache.attache_id
     *
     * @return the value of sys_attache.attache_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getAttacheId() {
        return attacheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attache.attache_id
     *
     * @param attacheId the value for sys_attache.attache_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setAttacheId(Integer attacheId) {
        this.attacheId = attacheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attache.file_type
     *
     * @return the value of sys_attache.file_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attache.file_type
     *
     * @param fileType the value for sys_attache.file_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attache.file_path
     *
     * @return the value of sys_attache.file_path
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attache.file_path
     *
     * @param filePath the value for sys_attache.file_path
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attache.create_date
     *
     * @return the value of sys_attache.create_date
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attache.create_date
     *
     * @param createDate the value for sys_attache.create_date
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attache.user_id
     *
     * @return the value of sys_attache.user_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attache.user_id
     *
     * @param userId the value for sys_attache.user_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}