package com.itany.nmms.entity;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item.product_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item.num
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item.order_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item.price
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item.id
     *
     * @return the value of sys_item.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item.id
     *
     * @param id the value for sys_item.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item.product_id
     *
     * @return the value of sys_item.product_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item.product_id
     *
     * @param productId the value for sys_item.product_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item.num
     *
     * @return the value of sys_item.num
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item.num
     *
     * @param num the value for sys_item.num
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item.order_id
     *
     * @return the value of sys_item.order_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item.order_id
     *
     * @param orderId the value for sys_item.order_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item.price
     *
     * @return the value of sys_item.price
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item.price
     *
     * @param price the value for sys_item.price
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}