package com.itany.nmms.entity;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.no
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.price
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.user_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.id
     *
     * @return the value of sys_order.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.id
     *
     * @param id the value for sys_order.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.no
     *
     * @return the value of sys_order.no
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.no
     *
     * @param no the value for sys_order.no
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.price
     *
     * @return the value of sys_order.price
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.price
     *
     * @param price the value for sys_order.price
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.user_id
     *
     * @return the value of sys_order.user_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.user_id
     *
     * @param userId the value for sys_order.user_id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}