package com.itany.nmms.entity;

public class ProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product_type.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product_type.name
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product_type.status
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    private Integer status;

    public ProductType(String name, Integer status) {
        this.name = name;
        this.status = status;
    }

    public ProductType() {
    }

    public ProductType(Integer id, String name, Integer status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product_type.id
     *
     * @return the value of sys_product_type.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product_type.id
     *
     * @param id the value for sys_product_type.id
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product_type.name
     *
     * @return the value of sys_product_type.name
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product_type.name
     *
     * @param name the value for sys_product_type.name
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product_type.status
     *
     * @return the value of sys_product_type.status
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product_type.status
     *
     * @param status the value for sys_product_type.status
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "ProductType{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", status=" + status +
                '}';
    }
}