package com.itany.nmms.dao;

import com.itany.nmms.entity.Order;
import com.itany.nmms.entity.OrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByPrimaryKey(Order record);
}