package com.itany.nmms.dao;

import com.itany.nmms.entity.ProductType;
import com.itany.nmms.entity.ProductTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int countByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int deleteByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    List<ProductType> selectByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    ProductType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByExample(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_type
     *
     * @mbggenerated Sat Aug 01 09:00:59 CST 2020
     */
    int updateByPrimaryKey(ProductType record);
}